import { test } from "node:test";
import assert from "node:assert/strict";
import { fixture, load } from "./manual-payment-idempotency.test";
const file="app/api/tenant/activate/route.ts";
const input={propertyId:"p",unitId:"u",tenantAssignmentId:"a",billingCycle:"2026-10",amountCents:10000,effectiveDate:new Date("2026-10-01")};
function rentFixture(){const f=fixture();const ensure=load(file,f.imports,"\nmodule.exports.ensureActivationRent = ensureActivationRent;").ensureActivationRent;return {...f,ensure};}
function row(extra:any={}){return {id:"old",...input,entryType:"CHARGE",chargeType:"RENT",voidedAt:null,idempotencyKey:"RENT:u:2026-10",...extra};}
test("activation writes canonical rent with unchanged cycle amount due date",async()=>{const f=rentFixture();await f.ensure(f.prisma,input);const r=f.state.ledgerEntry[0];assert.equal(r.idempotencyKey,"RENT:u:2026-10");assert.equal(r.billingCycle,"2026-10");assert.equal(r.amountCents,10000);assert.equal(r.effectiveDate.getTime(),input.effectiveDate.getTime());});
for(const key of ["RENT:u:2026-10",null])test("compatible rent retained without relabeling "+key,async()=>{const f=rentFixture();f.state.ledgerEntry.push(row({idempotencyKey:key}));await f.ensure(f.prisma,input);assert.equal(f.state.ledgerEntry.length,1);assert.equal(f.state.ledgerEntry[0].idempotencyKey,key);assert.equal(f.events.length,0);});
for(const change of [{tenantAssignmentId:"old-assignment"},{amountCents:1},{voidedAt:new Date()},{propertyId:"foreign"},{unitId:"foreign"},{billingCycle:"2026-09"},{idempotencyKey:"other"}])test("conflicting rent preserved and rejected "+JSON.stringify(change),async()=>{const f=rentFixture();f.state.ledgerEntry.push(row(change));const prior=JSON.stringify(f.state.ledgerEntry);await assert.rejects(f.ensure(f.prisma,input),(e:any)=>e.statusCode===409);assert.equal(JSON.stringify(f.state.ledgerEntry),prior);});
test("ambiguous rent fails closed",async()=>{const f=rentFixture();f.state.ledgerEntry.push(row(),row({id:"duplicate",idempotencyKey:null}));await assert.rejects(f.ensure(f.prisma,input),(e:any)=>e.statusCode===409);assert.equal(f.state.ledgerEntry.length,2);});
for(const same of [true,false])test("monthly overlap unique conflict "+same,async()=>{const f=rentFixture();f.prisma.ledgerEntry.createMany=async()=>{f.state.ledgerEntry.push(row({tenantAssignmentId:same?"a":"historical"}));return {count:0};};if(same)await f.ensure(f.prisma,input);else await assert.rejects(f.ensure(f.prisma,input),(e:any)=>e.statusCode===409);assert.equal(f.state.ledgerEntry.length,1);});
function activationFixture(){const f=fixture();f.state.tenantAssignment=[];f.imports["@prisma/client"].Prisma.TransactionIsolationLevel={Serializable:"Serializable"};const activate=async(body:any={})=>f.route(file).POST({json:async()=>({propertyCode:"1234",firstName:"First",lastName:"Last",unitNumber:"1",confirmUnitNumber:"1",tierId:"s",pin:"1234",confirmPin:"1234",recentMoveIn:false,moveInDate:null,...body})});return {...f,activate};}
for(const scenario of [{body:{},rent:true},{body:{recentMoveIn:true,moveInDate:"2026-09-30"},rent:true},{body:{recentMoveIn:true,moveInDate:"2026-10-02"},rent:false}])test("activation move-in rule "+JSON.stringify(scenario.body),async()=>{const f=activationFixture();const r=await f.activate(scenario.body);assert.equal(r.status,200);assert.equal(f.state.tenantAssignment.length,1);assert.equal(f.state.units[0].portalActivated,true);assert.equal(f.state.ledgerEntry.length,scenario.rent?1:0);});
test("pre-start activation posts no rent",async()=>{const f=activationFixture();f.imports["@/lib/rentDates"].getRentDateSummary=()=>({billingCycle:"2026-10",dueDate:"2026-10-01",hasStarted:false});assert.equal((await f.activate()).status,200);assert.equal(f.state.ledgerEntry.length,0);});
for(const change of [{isActive:false},{portalActivated:true}])test("existing activation eligibility retained "+JSON.stringify(change),async()=>{const f=activationFixture();Object.assign(f.state.units[0],change);assert.equal((await f.activate()).status,400);assert.equal(f.state.tenantAssignment.length,0);});
test("existing assigned unit rejected",async()=>{const f=activationFixture();f.state.tenantAssignment.push({id:"old",propertyId:"p",unitId:"u",isCurrent:true,moveOutDate:null});assert.equal((await f.activate()).status,409);assert.equal(f.state.units[0].portalActivated,undefined);});
test("conflicting historical canonical rent rolls back portal and assignment",async()=>{const f=activationFixture();f.state.ledgerEntry.push(row({tenantAssignmentId:"historical"}));assert.equal((await f.activate()).status,409);assert.equal(f.state.tenantAssignment.length,0);assert.equal(f.state.units[0].portalActivated,undefined);assert.equal(f.state.ledgerEntry[0].tenantAssignmentId,"historical");});
test("serialization retry rechecks changed eligibility",async()=>{const f=activationFixture();const original=f.prisma.$transaction;let calls=0;f.prisma.$transaction=async(fn:any,options:any)=>{calls++;if(calls===1){f.state.units[0].portalActivated=true;const K=f.imports["@prisma/client"].Prisma.PrismaClientKnownRequestError;throw new K("serialization",{code:"P2034"});}return original(fn,options);};assert.equal((await f.activate()).status,400);assert.equal(calls,2);assert.equal(f.state.tenantAssignment.length,0);});
