import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { runInNewContext } from "node:vm";
import ts from "typescript";
export const root = resolve(__dirname, "..");
export function load(file: string, imports: Record<string, any>, append = "", extras: any = {}) {
 const module = { exports: {} as any };
 const source = ts.transpileModule(readFileSync(resolve(root,file),"utf8")+append,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText;
 runInNewContext(source,{module,exports:module.exports,Date,Error,Buffer,URL,console:{error(){}},process:{env:{}},require(name:string){if(!(name in imports))throw Error("Unmocked import "+name);return imports[name];},...extras});return module.exports;
}
export const uuid = "11111111-1111-4111-8111-111111111111";
export const second = "22222222-2222-4222-8222-222222222222";
export function matches(row:any,where:any):boolean {return Object.entries(where??{}).every(([k,v]:[string,any])=>k==="OR"?v.some((p:any)=>matches(row,p)):k==="AND"?v.every((p:any)=>matches(row,p)):k==="NOT"?!matches(row,v):v&&typeof v==="object"&&!(v instanceof Date)?("in" in v?v.in.includes(row[k]):"contains" in v?row[k]?.includes(v.contains):"gt" in v?row[k]>v.gt:"lte" in v?row[k]<=v.lte:matches(row[k]??{},v)):row[k]===v);}
export function fixture(role:any="MANAGER") {
 const events:string[]=[];let sequence=0,tail=Promise.resolve();
 const property:any={id:"p",isActive:true,propertyCode:"1234",rentFrayStartDate:new Date("2026-01-01"),settings:{rentDueDay:1}};
 const tiers:any[]=[{id:"s",propertyId:"p",name:"Source",isActive:true,unitCount:3,activeUnitCount:1,baseRentCents:10000,rentDueDay:1},{id:"t",propertyId:"p",name:"Target",isActive:true,unitCount:1,activeUnitCount:0,baseRentCents:20000,rentDueDay:1}];
 const state:any={units:[{id:"u",unitNumber:"1",propertyId:"p",tierId:"s",isActive:true}],tenantAssignment:[{id:"a",propertyId:"p",unitId:"u",isCurrent:true,moveInDate:null,moveOutDate:null}],payment:[],ledgerEntry:[],auditLog:[]};
 const controls:any={fail:"",onLock:null,retries:0,cycle:"2026-10"};
 const expand=(row:any)=>row?{...row,tier:tiers.find(t=>t.id===row.tierId)??null,property,tenantAssignments:state.tenantAssignment.filter((a:any)=>a.unitId===row.id&&a.isCurrent)}:null;
 const write=(name:string)=>{events.push(name);if(controls.fail===name)throw Error("injected write failure");};
 const prisma:any={
  $executeRaw:async(strings:any,...values:any[])=>{events.push("advisory:"+values.join(":"));return 1;},
  $queryRaw:async(strings:any,...values:any[])=>{const sql=strings.join("?");events.push(sql);if(controls.onLock)await controls.onLock(sql,values);return [];},
  $transaction:async(fn:any,options:any)=>{const previous=tail;let release:any;tail=new Promise<void>(r=>release=r);await previous;const saved=structuredClone({state,tiers});events.push("begin:"+options?.isolationLevel);try{if(controls.retries>0){controls.retries--;throw {code:"P2034"};}return await fn(prisma);}catch(e){for(const k of Object.keys(state))state[k]=saved.state[k];tiers.splice(0,tiers.length,...saved.tiers);events.push("rollback");throw e;}finally{release();}},
  property:{findUnique:async()=>({...property,tiers})},
  propertyTier:{findFirst:async({where}:any)=>tiers.find(t=>matches(t,where))??null,update:async({where,data}:any)=>{write("tier.update");Object.assign(tiers.find(t=>t.id===where.id),data);},aggregate:async()=>({_sum:{unitCount:4}})},
  unit:{findFirst:async({where}:any)=>{events.push("unit.read");return expand(state.units.find((u:any)=>matches(u,where)));},findUnique:async({where}:any)=>expand(state.units.find((u:any)=>matches(u,where.propertyId_unitNumber??where))),count:async({where}:any)=>{events.push("capacity.read");return state.units.filter((u:any)=>matches(u,where)).length;},update:async({where,data}:any)=>{write("unit.update");const row=state.units.find((u:any)=>u.id===where.id);Object.assign(row,data);return {...row};},create:async({data}:any)=>{write("unit.create");const row={id:"new"+(++sequence),...data};state.units.push(row);return row;}},
 };
 for(const model of ["tenantAssignment","payment","ledgerEntry","auditLog"]){prisma[model]={findFirst:async({where}:any)=>state[model].find((r:any)=>matches(r,where))??null,findUnique:async({where}:any)=>state[model].find((r:any)=>matches(r,where))??null,findMany:async({where}:any)=>state[model].filter((r:any)=>matches(r,where)),count:async({where}:any)=>state[model].filter((r:any)=>matches(r,where)).length,create:async({data}:any)=>{write(model+".create");const row={id:model+(++sequence),createdAt:new Date("2026-10-05"),voidedAt:null,...data};state[model].push(row);return row;},updateMany:async({where,data}:any)=>{write(model+".updateMany");const rows=state[model].filter((r:any)=>matches(r,where));rows.forEach((r:any)=>Object.assign(r,data));return {count:rows.length};},createMany:async({data}:any)=>{let count=0;for(const row of data){if(row.idempotencyKey&&state[model].some((r:any)=>r.idempotencyKey===row.idempotencyKey))continue;await prisma[model].create({data:row});count++;}return {count};}};}
 class Known extends Error {code:string;constructor(message:string,{code}:any){super(message);this.code=code;}}
 const imports:any={"next/server":{NextResponse:{json:(body:any,options:any)=>({status:options?.status??200,body:JSON.parse(JSON.stringify(body))})}},"@prisma/client":{Prisma:{PrismaClientKnownRequestError:Known},PaymentStatus:{PAID:"PAID"}},"@/lib/prisma":{prisma},"@/lib/session":{getSession:async()=>role?{role,propertyId:"p",managementUserId:"m"}:null,requireRole:async(required:string)=>{if(role!==required)throw Error("Unauthorized");return {role,propertyId:"p"};},createSessionToken:async()=>"isolated",setSessionCookie:async()=>{}},"@/lib/permissions":{canManageFinancials:(r:string)=>["OWNER","MANAGER"].includes(r)},"@/lib/realtime":{emitEvent:()=>{}},"@/lib/rentDates":{resolveEffectiveBillingSettings:()=>({dueDay:1}),getRentDateSummary:()=>({billingCycle:controls.cycle,dueDate:"2026-10-01",hasStarted:true})},"@/lib/billingCalendar":{assertTierBillingCalendar:()=>1,BillingCalendarError:class extends Error {}},"@/lib/pin":{hashPin:async()=>"hash"},"@/jobs/lateFees":{runLateFeesJob:async()=>{}},"@/lib/destructiveRetention":{}};
 imports["@/lib/manualFinancialOperations"]=load("lib/manualFinancialOperations.ts",{});
 const route=(file:string)=>load(file,imports);
 const pay=async(body:any={})=>route("app/api/manual-payments/route.ts").POST({json:async()=>({unitId:"u",tenantAssignmentId:"a",operationId:uuid,amount:123.45,effectiveDate:"2026-10-05",...body})});
 const move=async(body:any={})=>route("app/api/manager/units/move-tier/route.ts").POST({json:async()=>({unitId:"u",targetTierId:"t",tenantAssignmentId:"a",expectedSourceTierId:"s",operationId:uuid,...body})});
 return {events,state,tiers,property,controls,prisma,imports,route,pay,move};
}
for(const role of ["OWNER","MANAGER"])test(role+" manual payment preserves paid/manual cents/cycle/attribution",async()=>{const f=fixture(role);const r=await f.pay();assert.equal(r.status,200);assert.equal(f.state.payment.length,1);assert.equal(f.state.ledgerEntry.length,1);assert.equal(f.state.auditLog.length,1);assert.equal(f.state.payment[0].status,"PAID");assert.equal(f.state.payment[0].paymentMethod,"MANUAL");assert.equal(f.state.ledgerEntry[0].amountCents,-12345);assert.equal(r.body.data.entry.billingCycle,"2026-10");assert.equal(r.body.data.entry.tenantAssignmentId,"a");});
for(const role of [null,"STAFF","TENANT","MAINTENANCE","ADMIN"])test(String(role)+" cannot post payment",async()=>{const f=fixture(role);assert.equal((await f.pay()).status,401);assert.equal(f.events.length,0);});
for(const body of [{tenantAssignmentId:"missing"},{tenantAssignmentId:""},{tenantId:"a",tenantAssignmentId:undefined},{unitId:"foreign"},{operationId:"bad"},{amount:0},{amount:-1},{amount:"NaN"},{amount:1000001},{effectiveDate:"bad"}])test("reject invalid payment "+JSON.stringify(body),async()=>{const f=fixture();assert.ok((await f.pay(body)).status>=400);assert.equal(f.state.payment.length,0);});
for(const change of [{isCurrent:false},{propertyId:"other"},{unitId:"other"},{moveOutDate:new Date("2000-01-01")},{moveInDate:new Date("2100-01-01")}])test("assignment eligibility "+JSON.stringify(change),async()=>{const f=fixture();Object.assign(f.state.tenantAssignment[0],change);assert.equal((await f.pay()).status,409);assert.equal(f.state.payment.length,0);});
test("identical replay returns original entry after vacancy and replacement",async()=>{const f=fixture();const first=await f.pay();f.state.tenantAssignment[0].isCurrent=false;f.state.tenantAssignment.push({id:"replacement",propertyId:"p",unitId:"u",isCurrent:true});const replay=await f.pay();assert.deepEqual(replay.body,first.body);assert.equal(f.state.payment.length,1);assert.equal(f.state.auditLog.length,1);});
for(const body of [{amount:124},{memo:"changed"},{effectiveDate:"2026-10-06"},{tenantAssignmentId:"replacement"},{unitId:"other"}])test("changed payment payload conflicts "+JSON.stringify(body),async()=>{const f=fixture();await f.pay();assert.equal((await f.pay(body)).status,409);assert.equal(f.state.payment.length,1);});
test("distinct operations permit same amount/date including overpayment",async()=>{const f=fixture();assert.equal((await f.pay({amount:10000})).status,200);assert.equal((await f.pay({amount:10000,operationId:second})).status,200);assert.equal(f.state.payment.length,2);assert.equal(f.state.ledgerEntry.reduce((s:number,r:any)=>s+r.amountCents,0),-2000000);});
for(const fail of ["payment.create","ledgerEntry.create","auditLog.create"])test("atomic rollback at "+fail,async()=>{const f=fixture();f.controls.fail=fail;assert.equal((await f.pay()).status,500);assert.equal(f.state.payment.length,0);assert.equal(f.state.ledgerEntry.length,0);assert.equal(f.state.auditLog.length,0);});
test("normalized memo/amount/UUID replay",async()=>{const f=fixture();const a=await f.pay({memo:" hello ",amount:123.45001});const b=await f.pay({memo:"hello",operationId:uuid.toUpperCase()});assert.deepEqual(a.body,b.body);assert.equal(f.state.payment.length,1);});
