import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fixture, load, root, uuid, second } from "./manual-payment-idempotency.test";
for(const operation of ["pay","move"] as const)test(operation+" advisory before rows; stable tier locks; reread after lock",async()=>{const f=fixture();assert.equal((await f[operation]()).status,200);const e=f.events;const advisors=e.map((x,i)=>x.startsWith("advisory:")?i:-1).filter(i=>i>=0);assert.equal(advisors.length,3);assert.ok(e[advisors[0]].includes("operation:"));assert.ok(e[advisors[1]].endsWith("p:u:a"));assert.ok(e[advisors[2]].endsWith("p:u:a:2026-10"));const property=e.findIndex(x=>x.includes('FROM "Property"'));assert.ok(advisors[2]<property);assert.ok(e[property].includes("NOWAIT"));const assignment=e.findIndex(x=>x.includes('FROM "TenantAssignment"'));const unit=e.findIndex(x=>x.includes('FROM "Unit"'));assert.ok(property<assignment&&assignment<unit);assert.ok(e.lastIndexOf("unit.read")>unit);const writes=e.findIndex(x=>x.endsWith(".create")||x.endsWith(".update"));assert.ok(writes>unit);});
for(const operation of ["pay","move"] as const)test(operation+" lock contention rolls back without writes",async()=>{const f=fixture();f.controls.onLock=()=>{throw {code:"P2010",meta:{code:"55P03"}};};assert.equal((await f[operation]()).status,409);assert.equal(f.state.payment.length,0);assert.equal(f.state.auditLog.length,0);assert.equal(f.state.units[0].tierId,"s");assert.ok(f.events.includes("rollback"));});
for(const operation of ["pay","move"] as const)test(operation+" bounded serialization retry",async()=>{const f=fixture();f.controls.retries=2;assert.equal((await f[operation]()).status,200);assert.equal(f.events.filter(x=>x.startsWith("begin:")).length,3);const exhausted=fixture();exhausted.controls.retries=4;assert.equal((await exhausted[operation]()).status,409);assert.equal(exhausted.events.filter(x=>x.startsWith("begin:")).length,3);assert.equal(exhausted.state.auditLog.length,0);});
for(const operation of ["pay","move"] as const)test(operation+" post-lock assignment revalidation",async()=>{const f=fixture();f.controls.onLock=(sql:string)=>{if(sql.includes('FROM "Property"'))f.state.tenantAssignment[0].isCurrent=false;};assert.equal((await f[operation]()).status,409);assert.equal(f.state.payment.length,0);assert.equal(f.state.auditLog.length,0);});
for(const operation of ["pay","move"] as const)test(operation+" changed provisional cycle rolls back",async()=>{const f=fixture();f.controls.onLock=(sql:string)=>{if(sql.includes('FROM "Property"'))f.controls.cycle="2026-11";};assert.equal((await f[operation]()).status,409);assert.equal(f.state.payment.length,0);assert.equal(f.state.auditLog.length,0);});
test("concurrent identical manual payment commits once",async()=>{const f=fixture();const r=await Promise.all([f.pay(),f.pay()]);assert.deepEqual(r[0].body,r[1].body);assert.equal(f.state.payment.length,1);});
function capacityFixture(){const f=fixture();f.state.units.push({id:"inactive",unitNumber:"2",propertyId:"p",tierId:"t",isActive:false});const reactivate=()=>{const imports={...f.imports,"@/lib/session":{requireManagerLevelSession:async()=>({role:"MANAGER",propertyId:"p"})}};return load("app/api/manager/units/toggle-active/route.ts",imports).POST({json:async()=>({unitId:"inactive",makeActive:true})});};const create=()=>{const imports={...f.imports,"@/lib/session":{getSession:async()=>({role:"ADMIN"})}};return load("app/api/admin/properties/[id]/units/route.ts",imports).POST({json:async()=>({tierId:"t",unitNumber:"3",baseRent:200})},{params:Promise.resolve({id:"p"})});};return {...f,reactivate,create};}
for(const pair of [["move","reactivate"],["move","create"],["reactivate","create"],["create","reactivate"],["reactivate","move"],["create","move"]] as const)test("final capacity slot "+pair.join(" vs "),async()=>{const f=capacityFixture();const r=await Promise.all([f[pair[0]](),f[pair[1]]()]);assert.equal(r.filter(x=>x.status===200).length,1);assert.equal(f.state.units.filter((u:any)=>u.tierId==="t"&&u.isActive).length,1);assert.equal(f.tiers[1].activeUnitCount,1);assert.ok(f.events.includes("rollback"));for(let i=0;i<f.events.length;i++)if(f.events[i]==="capacity.read")assert.ok(f.events.slice(0,i).some(x=>x.includes('FROM "Property"')));});
for(const operation of ["reactivate","create"] as const)test(operation+" first authoritative read follows shared property lock",async()=>{const f=capacityFixture();assert.equal((await f[operation]()).status,200);assert.ok(f.events[1].includes('FROM "Property"'));assert.ok(!f.events.some(x=>x.startsWith("advisory:")));assert.equal(f.state.ledgerEntry.length,0);});
test("stable sorted unique scoped tier locking",async()=>{const f=fixture();const h=f.imports["@/lib/manualFinancialOperations"];const ids:string[]=[];f.controls.onLock=(sql:string,values:any[])=>{if(sql.includes('FROM "PropertyTier"')){ids.push(values[0]);assert.equal(values[1],"p");}};await h.lockManualRows(f.prisma,"p","u","a",["z","a","z"]);assert.deepEqual(ids,["a","z"]);});
test("payment clients retain frozen UUID/payload until acknowledged; dashboard exposes assignment only",()=>{for(const file of ["app/manager/units/[id]/ManualPaymentForm.tsx","app/manager/dashboard/ManagerDashboardClient.tsx"]){const s=readFileSync(resolve(root,file),"utf8");assert.ok(s.includes("crypto.randomUUID()"));assert.ok(s.includes("tenantAssignmentId"));assert.ok(s.includes("JSON.stringify(operation)"));assert.ok(s.includes("useRef"));}const dashboard=readFileSync(resolve(root,"app/api/manager/dashboard/route.ts"),"utf8");assert.ok(dashboard.includes("tenantAssignmentId: assignment.id"));assert.ok(dashboard.includes("tenantAssignmentId: null"));});

function dashboardHandler(name:string,context:any){
 const ts = require("typescript");const source=readFileSync(resolve(root,"app/manager/dashboard/ManagerDashboardClient.tsx"),"utf8");const ast=ts.createSourceFile("dashboard.tsx",source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);let text="";
 function visit(n:any){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)text=n.getText(ast);ts.forEachChild(n,visit);}visit(ast);assert.ok(text);const vm=require("node:vm");const mod={exports:{} as any};vm.runInNewContext(ts.transpileModule(text+"\nmodule.exports.run="+name+";",{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:mod,exports:mod.exports,...context});return mod.exports.run;
}
for(const kind of ["payment","tier"])test("dashboard "+kind+" uncertain response freezes assignment amount date/source and UUID",async()=>{
 const sent:any[]=[];let clock="2026-10-05T23:59:00Z",ids=0,attempts=0;class Clock extends Date {constructor(){super(clock);}}
 const context:any={Date:Clock,crypto:{randomUUID:()=>++ids===1?uuid:second},selectedUnit:{unitId:"u",tierId:"s",tenantAssignmentId:"a"},movingTier:false,canVacateUnit:true,targetMoveTierId:"t",submittingManualPayment:false,canManageMoney:true,manualPaymentAmount:"123.45",paymentOperations:{current:{}},tierOperations:{current:{}},setMovingTier(){},setMoveTierError(){},setSubmittingManualPayment(){},setShowMoveTierModal(){},setTargetMoveTierId(){},setShowManualPaymentConfirm(){},closeUnitPanel(){},loadDashboard:async()=>{},loadPropertyTiers:async()=>{},alert(){},fetch:async(_:any,options:any)=>{sent.push(JSON.parse(options.body));if(++attempts===1)throw Error("response lost");return {ok:true,json:async()=>({ok:true})};}};
 const run=dashboardHandler(kind==="payment"?"submitManualPayment":"submitMoveTier",context);await run();clock="2026-10-06T00:01:00Z";context.selectedUnit.tenantAssignmentId="replacement";context.selectedUnit.tierId="t";await run();assert.deepEqual(sent[1],sent[0]);assert.equal(ids,1);assert.equal(sent[0].tenantAssignmentId,"a");if(kind==="payment")assert.equal(sent[0].effectiveDate,"2026-10-05");else assert.equal(sent[0].expectedSourceTierId,"s");const refs=kind==="payment"?context.paymentOperations:context.tierOperations;assert.equal(Object.keys(refs.current).length,0);await run();assert.equal(ids,2);assert.equal(sent[2].tenantAssignmentId,"replacement");
});
test("unit payment form freezes uncertain payload and clears only acknowledged completion",async()=>{
 const slots:any[]=[];let index=0,ids=0,attempt=0,refreshes=0;const sent:any[]=[];
 const react={useRef:(initial:any)=>{const i=index++;slots[i]??={current:initial};return slots[i];},useState:(initial:any)=>{const i=index++;if(!(i in slots))slots[i]=initial;return [slots[i],(v:any)=>slots[i]=v];}};
 const jsx=(type:any,props:any)=>({type,props});const component=load("app/manager/units/[id]/ManualPaymentForm.tsx",{"react":react,"react/jsx-runtime":{jsx,jsxs:jsx},"next/navigation":{useRouter:()=>({refresh:()=>refreshes++})}},"",{crypto:{randomUUID:()=>++ids===1?uuid:second},fetch:async(_:any,options:any)=>{sent.push(JSON.parse(options.body));if(++attempt===1)throw Error("uncertain");return {ok:true,json:async()=>({ok:true,data:{entry:{id:"entry"}}})};}}).default;
 let assignment="a";const render=()=>{index=0;return component({propertyId:"p",unitId:"u",tenantAssignmentId:assignment});};const inputs=(tree:any)=>tree.props.children.filter((x:any)=>x?.type==="input");let form=render();inputs(form)[0].props.onChange({target:{value:"123.456"}});inputs(form)[1].props.onChange({target:{value:"2026-10-05"}});inputs(form)[2].props.onChange({target:{value:" memo "}});form=render();await form.props.onSubmit({preventDefault(){}});assignment="replacement";form=render();assert.ok(inputs(form).every((x:any)=>x.props.disabled));await form.props.onSubmit({preventDefault(){}});assert.deepEqual(sent[1],sent[0]);assert.equal(ids,1);assert.equal(sent[0].amount,123.46);assert.equal(sent[0].memo,"memo");assert.equal(sent[0].tenantAssignmentId,"a");assert.equal(refreshes,1);form=render();assert.ok(inputs(form).every((x:any)=>!x.props.disabled));inputs(form)[0].props.onChange({target:{value:"1"}});form=render();await form.props.onSubmit({preventDefault(){}});assert.equal(ids,2);assert.equal(sent[2].tenantAssignmentId,"replacement");
});
