import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fixture, root } from "./manual-payment-idempotency.test";
for(const role of ["OWNER","MANAGER"])test(role+" retired proration has zero database access",async()=>{const f=fixture(role);const r=await f.route("app/api/ledger/adjust/route.ts").POST({json:async()=>({type:"PRORATION"})});assert.equal(r.status,410);assert.equal(f.events.length,0);assert.equal(f.state.ledgerEntry.length,0);});
test("unauthorized proration retains auth rejection",async()=>{const f=fixture("STAFF");assert.equal((await f.route("app/api/ledger/adjust/route.ts").POST({json:async()=>({type:"PRORATION"})})).status,401);assert.equal(f.events.length,0);});
test("UI contains no proration option/calculator",()=>{const s=readFileSync(resolve(root,"app/manager/dashboard/components/AdjustBalanceForm.tsx"),"utf8");assert.ok(!/proration/i.test(s));assert.ok(s.includes('setType("CHARGE")'));assert.ok(s.includes('setType("CREDIT")'));});
for(const type of ["CHARGE","CREDIT"])for(const blocked of [false,true])test(type+" retains amount/type/cycle deferral "+blocked,async()=>{const f=fixture();if(blocked)f.state.payment.push({id:"block",propertyId:"p",unitId:"u",tenantAssignmentId:"a",billingCycle:new Date().toISOString().slice(0,7),status:"PAID"});const r=await f.route("app/api/ledger/adjust/route.ts").POST({json:async()=>({unitId:"u",type,amount:12.34,memo:"custom"})});assert.equal(r.status,200);const entry=f.state.ledgerEntry[0];assert.equal(entry.amountCents,1234);assert.equal(entry.entryType,type);assert.equal(entry.chargeType,type==="CHARGE"?"OTHER_FEE":null);assert.equal(entry.tenantAssignmentId,"a");assert.equal(entry.memo,blocked?"custom (applies next billing cycle)":"custom");assert.equal(entry.idempotencyKey,undefined);});
